### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ggebbie** [ggebbie/OceanGreensFunctionMethods.jl#9]
- [ ] tests from MATLAB
- [ ] radio ages
- [ ] concentration ages
- [ ] transfer more equations from manuscript tables to docstrings
- [ ] figure 6 (box model schematic)
- [X] eigenvalue format consistent with Julia
- [x] figure 7
- [x] figure 8
- [x] figure 10
- [x] figure 11
- [x] figure 12
- [x] adjoint Green's function
- [x] RTD
- [x] path density
- [x] automatic deployment of documentation
- [x] docstrings for package functions
- [x] upstream fix for matrix left divide with units
- [x] check numerics of `ttd_width` for bug
- [x] tracer integration with QuadGK.jl https://github.com/JuliaMath/QuadGK.jl
- [x] iodine-129
- [x] argon-39
- [x] ideal ages (forward and adjoint)
- [x] multi-panel plots? (not needed in notebook form)
- [x] port Pluto notebook to Jupyter? (not needed, Pluto is working fine)
